CREATE TABLE [dbo].[TABLENAME](
	[SID] [varchar](40) NOT NULL,
	[CODE] [varchar](40) NULL,
	[NAME] [varchar](40) NULL,
	[REMARK] [varchar](max) NULL,
	[UDT] [datetime] NULL,
 CONSTRAINT [PK_BS_TABLENAME] PRIMARY KEY CLUSTERED 
(
	[SID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
;
CREATE TABLE [dbo].[TABLENAME_HT](
	[HID] [varchar](40) NOT NULL,
	[SID] [varchar](40) NOT NULL,
	[CODE] [varchar](40) NULL,
	[NAME] [varchar](15) NULL,
	[REMARK] [varchar](max) NULL,
	[UDT] [datetime] NULL,
	[TRANS] [varchar](20) NULL,
 CONSTRAINT [PK_BS_TABLENAME_HT] PRIMARY KEY CLUSTERED 
(
	[HID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]